server: 
  port: 8091
 
eureka: 
  instance:
    hostname: localhost #eureka服务端的实例名称(这里使用了虚拟主机映射，修改hosts文件即可实现)
    metadata-map:
      zone: zone-1
  client:
    healthcheck:
      # 一定要启用健康检查
      enabled: true
    register-with-eureka: true     #false表示不向注册中心注册自己。
    fetch-registry: true     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      #defaultZone: http://192.168.80.120:8081/eureka/,http://192.168.80.120:8082/eureka/
      zone-1: http://192.168.80.120:8081/eureka/
      zone-2: http://192.168.80.120:8082/eureka/
    prefer-same-zone-eureka: true #优先选择相同区域的
    region: jiangsu
    availability-zones:
      jiangsu: zone-1
      beijing: zone-2






feign:
  hystrix:
    #开启feign的hystrix支持,默认是false
    enabled: true
spring:
  application:
    name: hello-consumer

  freemarker:
    expose-spring-macro-helpers: true
    request-context-attribute: rc
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    prefer-file-system-access: true
    suffix: .ftl